-- ============================================================
-- ARTE ANIBA — Catálogo de productos
-- 002_seed_products.sql
-- Ejecutar después de 001. Inserta categorías y productos reales.
-- ============================================================

INSERT INTO categories (name, slug, description, sort_order) VALUES
    ('Hongos',       'hongos',       'Hongos decorativos tallados a mano en comino crespo recuperado. Cada pieza conserva grietas y colores propios de la madera.', 1),
    ('Lámparas',     'lamparas',     'Lámparas hongo con luz cálida, talladas en raíces de madera recuperada. Cada pieza es única.', 2),
    ('Corazones',    'corazones',    'Corazones decorativos tallados en raíces de comino crespo, sin lacas ni colorantes artificiales.', 3),
    ('Raíces',       'raices',       'Composiciones orgánicas de raíz recuperada con hongos tallados. Las medidas dependen de la naturaleza de las raíces.', 4),
    ('Candelabros',  'candelabros',  'Candelabros artesanales en forma de hongo con velas en cera de soya.', 5),
    ('Árboles',      'arboles',      'Árboles decorativos tallados en diferentes maderas recuperadas sosteniblemente.', 6),
    ('Maceteros',    'maceteros',    'Hongos maceteros para suculentas, cactus o plantas pequeñas.', 7),
    ('Cuadros',      'cuadros',      'Cuadros tridimensionales con hongos tallados sobre raíz dentro de marco de madera recuperada.', 8),
    ('Accesorios',   'accesorios',   'Dijes, charms y piezas pequeñas talladas en comino crespo.', 9),
    ('Porta Velas',  'porta-velas',  'Porta velas en forma de corazón tallados en raíces de madera recuperada.', 10);

INSERT INTO products (reference, name, slug, category_id, price, description, short_description, material, size, tone, stock_quantity, stock_alert_threshold, is_active, is_featured) VALUES

('1100', 'Hongo 8 cm',  'hongo-8cm',
    (SELECT id FROM categories WHERE slug = 'hongos'),
    27000,
    'Pieza pequeña tallada a mano en comino crespo recuperado. Ideal para escritorios, repisas y regalos artesanales. Cuenta con grietas y colores propios de la madera. Medidas pueden variar ya que el proceso es tallado artesanal.',
    'Pieza pequeña tallada a mano, ideal para escritorios y repisas.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '8 cm', 'from-clay to-walnut', 15, 3, TRUE, FALSE),

('1101', 'Hongo 10 cm', 'hongo-10cm',
    (SELECT id FROM categories WHERE slug = 'hongos'),
    40000,
    'Hongo decorativo de 10 cm tallado a mano en comino crespo recuperado. Cada pieza es única con grietas y colores naturales de la madera.',
    'Hongo decorativo de 10 cm, perfecto para estantes y mesas.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '10 cm', 'from-clay to-walnut', 12, 3, TRUE, FALSE),

('1102', 'Hongo 15 cm', 'hongo-15cm',
    (SELECT id FROM categories WHERE slug = 'hongos'),
    56000,
    'Hongo decorativo de 15 cm con presencia notable. Tallado a mano en comino crespo recuperado, cada pieza conserva las grietas y vetas naturales de la raíz.',
    'Hongo de 15 cm con presencia notable, formato versátil.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '15 cm', 'from-night to-clay', 10, 3, TRUE, FALSE),

('1103', 'Hongo 20 cm', 'hongo-20cm',
    (SELECT id FROM categories WHERE slug = 'hongos'),
    80000,
    'Pieza de 20 cm que destaca en salas, comedores y recibidores. Tallada a mano sin moldes, en raíz de comino crespo recuperado.',
    'Pieza de 20 cm ideal para salas, comedores y recibidores.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '20 cm', 'from-moss to-walnut', 8, 3, TRUE, FALSE),

('1104', 'Hongo 25 cm', 'hongo-25cm',
    (SELECT id FROM categories WHERE slug = 'hongos'),
    150000,
    'Escultura de 25 cm con carácter y volumen. Tallada a mano en comino crespo de raíces de 70 a 100 años recuperadas de bosques locales.',
    'Escultura de 25 cm con carácter y volumen para espacios amplios.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '25 cm', 'from-walnut to-clay', 6, 2, TRUE, FALSE),

('1105', 'Hongo 30 cm', 'hongo-30cm',
    (SELECT id FROM categories WHERE slug = 'hongos'),
    270000,
    'Hongo de formato grande (30 cm) que se convierte en protagonista visual del espacio. Tallado artesanalmente en comino crespo recuperado.',
    'Formato grande protagonista para hoteles, lobbies e interiorismo.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '30 cm', 'from-clay-dark to-clay', 4, 2, TRUE, TRUE),

('1106', 'Hongo 40 cm', 'hongo-40cm',
    (SELECT id FROM categories WHERE slug = 'hongos'),
    570000,
    'Pieza escultórica de 40 cm para coleccionistas, decoradores y proyectos especiales. Cada hongo de este tamaño es una obra de arte natural.',
    'Pieza escultórica de 40 cm para coleccionistas y proyectos especiales.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '40 cm', 'from-night to-walnut', 2, 1, TRUE, FALSE),

('1107', 'Hongo 50 cm', 'hongo-50cm',
    (SELECT id FROM categories WHERE slug = 'hongos'),
    720000,
    'Escultura protagonista de 50 cm para espacios amplios, hoteles, salas y vitrinas de gran formato. Pieza de colección que transforma cualquier ambiente.',
    'Escultura protagonista de 50 cm para hoteles y salas de gran formato.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '50 cm', 'from-clay to-night', 2, 1, TRUE, TRUE),

('1155', 'Lámpara hongo 25 cm', 'lampara-hongo-25cm',
    (SELECT id FROM categories WHERE slug = 'lamparas'),
    260000,
    'Lámpara cálida y artesanal para mesas auxiliares, mesas de noche o rincones de lectura. Tallada en raíz de comino crespo recuperado con luz cálida integrada.',
    'Lámpara cálida para mesas auxiliares y rincones de lectura.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales, y luz cálida.',
    '25 cm', 'from-clay to-night', 5, 2, TRUE, FALSE),

('1156', 'Lámpara hongo 30 cm', 'lampara-hongo-30cm',
    (SELECT id FROM categories WHERE slug = 'lamparas'),
    382000,
    'Formato equilibrado para sala, lobby o dormitorio con iluminación suave. Cada lámpara es única, tallada a mano en comino crespo recuperado.',
    'Formato equilibrado para sala, lobby o dormitorio.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales, y luz cálida.',
    '30 cm', 'from-walnut to-clay', 4, 2, TRUE, TRUE),

('1157', 'Lámpara hongo 40 cm', 'lampara-hongo-40cm',
    (SELECT id FROM categories WHERE slug = 'lamparas'),
    582000,
    'Lámpara de acento con altura y carácter para proyectos decorativos de gran formato. Tallada en comino crespo recuperado.',
    'Lámpara de acento con altura y carácter para proyectos decorativos.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales, y luz cálida.',
    '40 cm', 'from-night to-moss', 3, 1, TRUE, FALSE),

('1117', 'Hongo macetero 15 cm', 'hongo-macetero-15cm',
    (SELECT id FROM categories WHERE slug = 'maceteros'),
    36000,
    'Macetero en forma de hongo para suculentas, cactus o plantas pequeñas. Tallado en raíz de comino crespo recuperado.',
    'Macetero hongo para suculentas, cactus o plantas pequeñas.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '15 cm', 'from-moss to-walnut', 20, 5, TRUE, FALSE),

('1111', 'Candelabro hongo 10 cm', 'candelabro-hongo-10cm',
    (SELECT id FROM categories WHERE slug = 'candelabros'),
    40000,
    'Candelabro artesanal con silueta orgánica para mesas, rituales y decoración cálida. Incluye vela en cera de soya con aroma delicioso.',
    'Candelabro artesanal con vela en cera de soya.',
    'Raíces de madera recuperada. Velas elaboradas en cera de soya.',
    '10 cm', 'from-walnut to-clay', 15, 5, TRUE, FALSE),

('1112', 'Candelabro hongo 15 cm', 'candelabro-hongo-15cm',
    (SELECT id FROM categories WHERE slug = 'candelabros'),
    56000,
    'Candelabro mediano con presencia en mesa. Cada pieza es única por la naturaleza de la raíz de comino crespo recuperado.',
    'Candelabro mediano con vela de cera de soya.',
    'Raíces de madera recuperada. Velas elaboradas en cera de soya.',
    '15 cm', 'from-clay-dark to-clay', 10, 3, TRUE, FALSE),

('1113', 'Candelabro hongo 20 cm', 'candelabro-hongo-20cm',
    (SELECT id FROM categories WHERE slug = 'candelabros'),
    80000,
    'Candelabro de formato grande con silueta orgánica imponente. Tallado a mano en comino crespo de raíces centenarias recuperadas.',
    'Candelabro grande con silueta orgánica imponente.',
    'Raíces de madera recuperada. Velas elaboradas en cera de soya.',
    '20 cm', 'from-night to-clay', 6, 2, TRUE, FALSE),

('1140', 'Raíz con 3 hongos', 'raiz-3-hongos',
    (SELECT id FROM categories WHERE slug = 'raices'),
    230000,
    'Composición orgánica de raíz recuperada con tres hongos tallados. Este producto no tiene medida estandarizada ya que depende de la naturaleza de las raíces. Medida aproximada: 28×14 cm.',
    'Composición orgánica de raíz con tres hongos tallados.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '28×14 cm (aprox)', 'from-moss to-clay', 5, 2, TRUE, FALSE),

('1141', 'Raíz con 5 hongos', 'raiz-5-hongos',
    (SELECT id FROM categories WHERE slug = 'raices'),
    300000,
    'Obra de mesa con ritmo natural y diferentes alturas. Cinco hongos emergen de una raíz recuperada de comino crespo. Medida aproximada: 37×23 cm.',
    'Obra de mesa con cinco hongos y ritmo natural.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '37×23 cm (aprox)', 'from-walnut to-night', 4, 2, TRUE, TRUE),

('1142', 'Raíz con 7 hongos', 'raiz-7-hongos',
    (SELECT id FROM categories WHERE slug = 'raices'),
    420000,
    'Pieza escultórica de mayor escala para coleccionistas y proyectos especiales. Siete hongos tallados emergen de una raíz centenaria de comino crespo. Medida aproximada: 45×27 cm.',
    'Pieza escultórica de mayor escala para coleccionistas.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '45×27 cm (aprox)', 'from-clay-dark to-moss', 3, 1, TRUE, FALSE),

('1163', 'Árbol decorativo 20 cm', 'arbol-20cm',
    (SELECT id FROM categories WHERE slug = 'arboles'),
    48000,
    'Figura de árbol tallada a mano en diferentes maderas recuperadas sosteniblemente: mataratón, cedro y comino.',
    'Árbol tallado en maderas recuperadas, ideal para regalos.',
    'Diferentes maderas recuperadas sosteniblemente: mataratón, cedro y comino.',
    '20 cm', 'from-moss to-clay-soft', 12, 3, TRUE, FALSE),

('1159-arbol', 'Árbol decorativo 25 cm', 'arbol-25cm',
    (SELECT id FROM categories WHERE slug = 'arboles'),
    68000,
    'Árbol mediano tallado en maderas recuperadas con colores variados que dependen de la naturaleza de cada pieza.',
    'Árbol mediano con colores variados de la madera.',
    'Diferentes maderas recuperadas sosteniblemente: mataratón, cedro y comino.',
    '25 cm', 'from-clay to-walnut', 8, 3, TRUE, FALSE),

('1160-arbol', 'Árbol decorativo 30 cm', 'arbol-30cm',
    (SELECT id FROM categories WHERE slug = 'arboles'),
    99000,
    'Árbol grande tallado en maderas recuperadas sosteniblemente. Colores variados que dependen de la naturaleza de las raíces.',
    'Árbol grande en maderas recuperadas, proceso artesanal.',
    'Diferentes maderas recuperadas sosteniblemente: mataratón, cedro y comino.',
    '30 cm', 'from-walnut to-clay', 6, 2, TRUE, FALSE),

('1133', 'Corazón con base 15 cm', 'corazon-base-15cm',
    (SELECT id FROM categories WHERE slug = 'corazones'),
    220000,
    'Corazón decorativo con base natural, una pieza con presencia y veta única. Tallado a mano en raíz de comino crespo recuperado.',
    'Corazón con base natural, presencia y veta única.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '15×15 cm', 'from-clay-dark to-clay', 4, 2, TRUE, FALSE),

('1134', 'Corazón con base 20 cm', 'corazon-base-20cm',
    (SELECT id FROM categories WHERE slug = 'corazones'),
    315000,
    'Formato grande para regalos memorables, vitrinas o interiores de autor. Tallado a mano en comino crespo recuperado.',
    'Formato grande para regalos memorables y vitrinas.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '20×20 cm', 'from-night to-walnut', 3, 1, TRUE, TRUE),

('1158', 'Corazón sin base 12 cm', 'corazon-sin-base-12cm',
    (SELECT id FROM categories WHERE slug = 'corazones'),
    50000,
    'Pieza ligera y expresiva, tallada respetando grietas y tonos naturales del comino crespo recuperado. Cada corazón es diferente.',
    'Pieza ligera y expresiva con grietas y tonos naturales.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '12×12 cm', 'from-clay to-clay-soft', 10, 3, TRUE, FALSE),

('1159-porta', 'Porta velas corazón', 'porta-velas-corazon',
    (SELECT id FROM categories WHERE slug = 'porta-velas'),
    56000,
    'Porta velas en forma de corazón tallado a mano en raíz de comino crespo recuperado. Incluye espacio para vela tipo tealight.',
    'Porta velas corazón con espacio para vela tealight.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '20×20 cm', 'from-clay to-walnut', 8, 3, TRUE, FALSE),

('1160-dije', 'Dije hongo (charm)', 'dije-hongo-charm',
    (SELECT id FROM categories WHERE slug = 'accesorios'),
    20000,
    'Dije o charm en forma de hongo tallado a mano en comino crespo recuperado. Tamaño entre 1,5 y 3 cm.',
    'Dije hongo tallado a mano, ideal como regalo o accesorio.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '1,5–3 cm', 'from-moss to-clay-soft', 30, 5, TRUE, FALSE),

('1160-cuadro', 'Cuadro de hongos', 'cuadro-hongos',
    (SELECT id FROM categories WHERE slug = 'cuadros'),
    235000,
    'Cuadro tridimensional con hongos tallados sobre raíz dentro de marco de madera recuperada. Cada uno es diferente, con formas y texturas naturales.',
    'Cuadro 3D con hongos tallados sobre raíz enmarcada.',
    'Raíces de madera recuperada de talas ancestrales, sin lacas o colorantes artificiales.',
    '35×24 cm', 'from-clay-dark to-moss', 3, 1, TRUE, TRUE);
